In [5]:
import pandas as pd
import numpy as np

In [6]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [7]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [12]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])

In [13]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [14]:
from numpy.random import randn

In [15]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

          W         X         Y         Z
A -0.063998  0.030751 -1.291226  0.038717
B -0.543820 -0.454071 -0.804698  0.239756
C  0.788419  0.329134  1.321504 -0.147483
D  1.104094 -1.135950 -0.608747 -0.089310
E -0.137464  0.239227  1.985461  0.332648

In [16]:
df['W']

A   -0.063998
B   -0.543820
C    0.788419
D    1.104094
E   -0.137464
Name: W, dtype: float64

In [17]:
df.loc['A']

W   -0.063998
X    0.030751
Y   -1.291226
Z    0.038717
Name: A, dtype: float64

In [18]:
df.iloc[2]

W    0.788419
X    0.329134
Y    1.321504
Z   -0.147483
Name: C, dtype: float64

In [19]:
df.loc[['A','B'],['W','Y']]

          W         Y
A -0.063998 -1.291226
B -0.543820 -0.804698

Missing data

In [22]:
df = pd.DataFrame({'A':[1,2,np.nan],
'B':[5,np.nan,np.nan],
'C':[1,2,3]})
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [23]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [24]:
df.dropna(axis=0)

     A    B  C
0  1.0  5.0  1

In [25]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [26]:
df['A'].fillna(value=df['A'].mean(),inplace=True)
df

/tmp/ipykernel_7395/736070674.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(value=df['A'].mean(),inplace=True)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

In [27]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [32]:
by_comp = df.groupby("Company")
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [33]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']},
index=[0, 1, 2, 3])

In [34]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
'B': ['B4', 'B5', 'B6', 'B7'],
'C': ['C4', 'C5', 'C6', 'C7'],
'D': ['D4', 'D5', 'D6', 'D7']},
index=[4, 5, 6, 7])

In [35]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [36]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [37]:
pd.concat([df1,df2],axis=1)

     A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7